'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3053
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class _Default

    '''<summary>
    '''styleLiteral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents styleLiteral As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''styleLiteral1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents styleLiteral1 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''myBody control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents myBody As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Literal1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Literal1 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''loginPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loginPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''f_userName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents f_userName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''f_password control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents f_password As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''loginButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loginButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''changePasswordButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents changePasswordButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cpRow_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cpRow_1 As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''newPasswordTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents newPasswordTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cpRow_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cpRow_2 As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''newPasswordAgainTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents newPasswordAgainTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cpRow_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cpRow_3 As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''confirmChangePasswordButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents confirmChangePasswordButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''changePasswordResponseLegacy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents changePasswordResponseLegacy As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loginPanelNewInterface control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loginPanelNewInterface As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''userNameNewInterface control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents userNameNewInterface As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''passwordNewInterface control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents passwordNewInterface As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''loginButtonNewInterface control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loginButtonNewInterface As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''changePasswordButtonNewInterface control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents changePasswordButtonNewInterface As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''changePasswordResponseNewInterface control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents changePasswordResponseNewInterface As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''changePasswordPanelNewInterface control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents changePasswordPanelNewInterface As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''newPasswordTextBoxNewInterface control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents newPasswordTextBoxNewInterface As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''newPasswordAgainTextBoxNewInterface control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents newPasswordAgainTextBoxNewInterface As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''confirmChangePasswordButtonNewInterface control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents confirmChangePasswordButtonNewInterface As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''loginPanelBS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loginPanelBS As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''f_bs_userName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents f_bs_userName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''userNameBS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents userNameBS As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''f_bs_password control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents f_bs_password As Global.System.Web.UI.HtmlControls.HtmlInputPassword

    '''<summary>
    '''passwordBS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents passwordBS As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Button1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''registerButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents registerButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''registerPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents registerPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''responseTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents responseTable As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''changePasswordResponse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents changePasswordResponse As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''myPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents myPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''myWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents myWidth As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''legacyActionPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents legacyActionPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''downloadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents downloadButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ddDownLoadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddDownLoadButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''csvDownLoadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents csvDownLoadButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ddCSVDownLoadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddCSVDownLoadButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''runReportButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents runReportButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''doneButtonPlaceHolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents doneButtonPlaceHolder As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''doneButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents doneButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''legacyReportSelectionPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents legacyReportSelectionPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''timeSpanDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents timeSpanDropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ignoreTimeCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ignoreTimeCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''startTimeDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents startTimeDropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents label2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''endTimeDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents endTimeDropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''calendar1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calendar1 As Global.System.Web.UI.WebControls.Calendar

    '''<summary>
    '''calendar2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calendar2 As Global.System.Web.UI.WebControls.Calendar

    '''<summary>
    '''myTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents myTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''myLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents myLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''radioList1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radioList1 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''clearSelectionButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents clearSelectionButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''groupNameListBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents groupNameListBox As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''selectedUsersListBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents selectedUsersListBox As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''typeOfReportLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents typeOfReportLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''typeOfReportListBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents typeOfReportListBox As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''newInterfaceActionPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents newInterfaceActionPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''newInterfaceDownloadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents newInterfaceDownloadButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''newInterfaceDDDownloadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents newInterfaceDDDownloadButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''newInterfaceCSVDownloadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents newInterfaceCSVDownloadButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''newInterfaceDDCSVDownloadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents newInterfaceDDCSVDownloadButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''runReportButtonnewInterface control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents runReportButtonnewInterface As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''newInterfaceReportSelectionPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents newInterfaceReportSelectionPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''timeSpanNewInterfaceDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents timeSpanNewInterfaceDropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ignoreTimeNewInterfaceCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ignoreTimeNewInterfaceCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''startTimeNewInterfaceLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents startTimeNewInterfaceLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''startTimeNewInterfaceDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents startTimeNewInterfaceDropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''endTimeNewInterfaceLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents endTimeNewInterfaceLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''endTimeNewInterfaceDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents endTimeNewInterfaceDropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''calendar3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calendar3 As Global.System.Web.UI.WebControls.Calendar

    '''<summary>
    '''calendar4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calendar4 As Global.System.Web.UI.WebControls.Calendar

    '''<summary>
    '''clearSelectionButtonNewInterface control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents clearSelectionButtonNewInterface As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''RadioButtonList1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonList1 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''groupNameNewInterfaceListBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents groupNameNewInterfaceListBox As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''typeOfReportNewInterfaceListBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents typeOfReportNewInterfaceListBox As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''selectedUsersNewInterfaceListBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents selectedUsersNewInterfaceListBox As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''actionPanelBS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents actionPanelBS As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''actionDownloadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents actionDownloadButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''actionCSVDownloadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents actionCSVDownloadButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ddActionPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddActionPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ddActionDownloadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddActionDownloadButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ddActionCSVDownloadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddActionCSVDownloadButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''searchPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents searchPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''f_startDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents f_startDate As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''f_endDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents f_endDate As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''Button2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button2 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Button3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button3 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Button4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button4 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''bs_calendar1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bs_calendar1 As Global.System.Web.UI.WebControls.Calendar

    '''<summary>
    '''bs_calendar2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bs_calendar2 As Global.System.Web.UI.WebControls.Calendar

    '''<summary>
    '''startTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents startTime As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''timeModeDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents timeModeDropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''logoutButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents logoutButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''endTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents endTime As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''sortExtensionsBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sortExtensionsBy As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Button5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button5 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''timeSpan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents timeSpan As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''groupName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents groupName As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''reportType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reportType As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''reportedExtensions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reportedExtensions As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''fileUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fileUpload As Global.System.Web.UI.HtmlControls.HtmlInputFile

    '''<summary>
    '''uploadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uploadButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cogs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cogs As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''logLiteral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents logLiteral As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''myLiteral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents myLiteral As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''reportPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reportPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Literal2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Literal2 As Global.System.Web.UI.WebControls.Literal
End Class
